# Generated by Django 5.1.2 on 2024-11-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='цена'),
        ),
    ]
